#!/bin/bash
set -xeuo pipefail

: ${BUILD_NEXTSTRAIN_CLI_VERSION:?You must provide a nextstrain-cli version for which to push wheels/pex.}

cd "$(dirname $0)/.."

# Decrypt SSH key which lets us push to GitHub
ssh_key=.travis/id_rsa

cp $ssh_key $ssh_key.dec
chmod u=r,go= $ssh_key.dec

ssh-keygen -p -f $ssh_key.dec -P "$SSH_KEY_PASSPHRASE" -N "" || rm $ssh_key.dec

# Report status for diagnostics
git status

# Add a destination remote under our control instead of relying on the remote
# Travis created
remote=github
branch=travis/$TRAVIS_BUILD_NUMBER

GIT_SSH=.travis/ssh-wrapper \
    git remote add -f $remote git@github.com:$TRAVIS_REPO_SLUG.git

# Create a new local branch, e.g. travis/42
git checkout -b $branch

# Add any new or modified files
git add .
git commit --file /dev/stdin

# Rebase local branch onto remote branch, if it exists
if git rev-parse --verify $remote/$branch; then
    GIT_SSH=.travis/ssh-wrapper \
        git pull --rebase $remote $branch
fi

GIT_SSH=.travis/ssh-wrapper \
    git push $remote HEAD:$branch
