#!/bin/bash
set -xeuo pipefail

: ${BUILD_NEXTSTRAIN_CLI_VERSION:?You must provide a nextstrain-cli version for which to push wheels.}

"$(dirname $0)"/push <<.
Wheels for nextstrain-cli==$BUILD_NEXTSTRAIN_CLI_VERSION built on $(uname) via Travis CI

$TRAVIS_JOB_WEB_URL
.
