#!/bin/bash
set -xeuo pipefail

exec docker run \
  --rm \
  --env BUILD_NEXTSTRAIN_CLI_VERSION \
  --env TRAVIS_BUILD_NUMBER \
  --env TRAVIS_REPO_SLUG \
  --volume $(pwd):/mnt \
  --workdir /mnt \
  "$@"
